### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by starlightretailceo** [Azure-Samples/ai-hub-gateway-solution-accelerator#15]
![IMG_1429](https://github.com/user-attachments/assets/c56d10c5-b702-47fa-9abc-b1de44a16377)
![IMG_1430](https://github.com/user-attachments/assets/9913cdbd-153f-4c1b-a0cf-9102a8f0a7ae)
IT WILL KILL YOUR SUBSCRIPTION AND YOUR WHOLE AZURE JOURNEY WILL BE EXTREMELY ABUSED TO AN EXTENT THEY WONT REPLY YOU. IM A FOUNDERS HUB MEMBER THEY BURNT MY BOTH SUBSCRIPTION MIDWAY OF DEPLOYMENT DRAMATIZING I VIOLATED THEIR POLICY ITS BULLSHIT THAT SUCH SAMPLES ARE POSTED BY THEM TO THEN LATER ABUSE PREMIER PARTNERS AND ISV's

**Comment by starlightretailceo** [comment]
You should be applauded because of this sample i lost 1244 resources that were belonging to my startup founders hub subscription because of this reckless git i got 5 subscription disabled as soon as i deploy this they blow off the subscription shame on microsoft to author the git on azure samples

**Comment by starlightretailceo** [comment]
@msftgits @microsoftopensource

**Comment by mohamedsaif** [comment]
NA
