### ISSUE TITLE
Route AOAI request to a new instance

### ISSUE THREAD

**Issue by kalalvishal** [Azure-Samples/ai-hub-gateway-solution-accelerator#22]
I followed the instructions to “Onboarding an OpenAI Instance” guide to onboard a new instance of AOAI. So far, I have completed the following steps:

- Created a new instance of AOAI in the East US region and deployed the GPT-35-Turbo model with the deployment name “chat”
- Created an APIM backend for OpenAI with /openai/.
- Granted OpenAI user access to the APIM user-managed identity.
- Updated the routing configuration to rev2.
  
      routes.Add(new JObject()
        {
            { "name", "EastUS" },
            { "location", "eastus" },
            { "backend-id", "openai-backend-0" },
            { "priority", 1},
            { "isThrottling", false }, 
            { "retryAfter", DateTime.MinValue } 
        });

      routes.Add(new JObject()
        {
            { "name", "NorthCentralUS" },
            { "location", "northcentralus" },
            { "backend-id", "openai-backend-1" },
            { "priority", 2},
            { "isThrottling", false },
            { "retryAfter", DateTime.MinValue }
        });

      routes.Add(new JObject()
        {
            { "name", "EastUS2" },
            { "location", "eastus2" },
            { "backend-id", "openai-backend-2" },
            { "priority", 2},
            { "isThrottling", false },
            { "retryAfter", DateTime.MinValue }
        });
      
      routes.Add(new JObject()
        {
            { "name", "EastUS-Instance-02" },
            { "location", "eastus" },
            { "backend-id", "openai-backend-3" },
            { "priority", 1},
            { "isThrottling", false },
            { "retryAfter", DateTime.MinValue }
        });

- modified the cluster:
` 
clusters.Add(new JObject()
    {
        { "deploymentName", "chat" },
        { "routes", new JArray(routes[0], routes[1], routes[2], routes[3]) }
    });
`

I am sending the request to rev2. Here is the reference URL: 
`https://apiminstancename.azure-api.net/openai;rev=2/deployments/chat/chat/completions?api-version=2024-06-01&subscription-key=apim-subscription-key` 

I still don’t see the request routing to the new instance that I added. APIM logs for reference:

![apim-aoai-snapshot](https://github.com/user-attachments/assets/473977f9-4d8e-4594-9554-3d3e6963d41c)

Please suggest if I am missing something. Thank you.

**Comment by mohamedsaif** [comment]
Thanks @kalalvishal for reaching out.
Can you please confirm if you created the revision before or after adding the configurations? It seems cache issue. You can create a new revision and validate.
Correct order of things is revision must be created first before applying the configuration change.

**Comment by kalalvishal** [comment]
> Thanks @kalalvishal for reaching out. Can you please confirm if you created the revision before or after adding the configurations? It seems cache issue. You can create a new revision and validate. Correct order of things is revision must be created first before applying the configuration change.

Hello @mohamedsaif, yes it was caching issue. As you corrected mentioned, creating of the revision before or after (adding the configurations fixed the issue. Thank you.
