### ISSUE TITLE
Proposal: Lock Down Public Network Access for Cognitive Services Account

### ISSUE THREAD

**Issue by aymenfurter** [Azure-Samples/ai-hub-gateway-solution-accelerator#6]
#### Current Resource Configuration:
```bicep
resource account 'Microsoft.CognitiveServices/accounts@2023-05-01' = {
  name: name
  location: location
  tags: union(tags, { 'azd-service-name': name })
  kind: kind
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    customSubDomainName: name
  }
  sku: sku
}
```

#### Relevant Code Snippet:
From the [AI Hub Gateway Solution Accelerator](https://github.com/Azure-Samples/ai-hub-gateway-solution-accelerator/blob/7b00890683ac3a1f9203423832aff39b58914405/infra/modules/ai/cognitiveservices.bicep#L16):
```bicep
resource symbolicname 'Microsoft.CognitiveServices/accounts@2023-05-01' = {
  name: 'string'
  location: 'string'
  // other properties
  properties: {
    // implicitly enabled by not setting publicNetworkAccess to 'Disabled'
  }
}
```

### Proposal:
To enhance security, I propose locking down the public network access (i.e., public endpoint) so that communication can exclusively flow through API Management.

#### Required Changes:
- Set `publicNetworkAccess` to `Disabled`
- Configure DNS and network settings appropriately

#### Benefits / Rationale:
Many customers prefer to minimize their public infrastructure footprint for security reasons. Implementing this change will help meet this requirement.

**Documentation Reference:**
For more details, refer to the [Microsoft Documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.cognitiveservices/2023-05-01/accounts?pivots=deployment-language-bicep#accountproperties).

Could this be considered for implementation? Many customers would appreciate this added security feature.

**Comment by mohamedsaif** [comment]
@aymenfurter Thanks for your feedback.
It is very important indeed and currently being implemented and will be published with the next update of the gateway.

**Comment by aymenfurter** [comment]
(Work in progress) https://github.com/aymenfurter/ai-hub-gateway-solution-accelerator/commit/62c42bc7140ed773e7cc3e9fdf7590d30534f154
